### ISSUE TITLE
Add a pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/drat#10]
What's the workflow for adding a pkg? i should probably know :(

**Comment by cboettig** [comment]
Anything listed by ropkgs should be pulled in automatically...  https://github.com/ropensci/drat/blob/gh-pages/ropensci.R 

but I think the aws deploy is timing out recently ( due to download logs) so we need to debug.

**Comment by sckott** [comment]
okay, thanks

**Comment by sckott** [comment]
ah, I see - all roregistry pkgs are under ropensci org - i was trying to add `AndySouth/rnaturalearthhires` via https://github.com/ropensci/onboarding/issues/22#issuecomment-199559363

Perhaps that goes here  https://github.com/ropensci/drat/blob/gh-pages/packages.txt ?

**Comment by cboettig** [comment]
Yup! (Sorry, forgot we were talking about a package that isn't on ropensci
github)

On Tue, Mar 22, 2016, 6:50 PM Scott Chamberlain notifications@github.com
wrote:

> ah, I see - all roregistry pkgs are under ropensci org - i was trying to
> add AndySouth/rnaturalearthhires via ropensci/onboarding#22 (comment)
> https://github.com/ropensci/onboarding/issues/22#issuecomment-199559363
> 
> Perhaps that goes here
> https://github.com/ropensci/drat/blob/gh-pages/packages.txt ?
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/drat/issues/10#issuecomment-200121913
> 
> ## 

http://carlboettiger.info
