### ISSUE TITLE
Build failing?

### ISSUE THREAD

**Issue by cboettig** [ropensci/drat#12]
@sckott circle-ci build seems to be timing out on  fetching ropensci/apipkgen --- is that a private package? (Seems to be asking for github author, I just get a 404 at that pkg).  Any ideas?

**Comment by sckott** [comment]
Sorry, should be ropenscilabs

**Comment by sckott** [comment]
Will fix in an hour or so

**Comment by sckott** [comment]
hmm, the json file has the right url https://github.com/ropensci/roregistry/blob/master/registry.json#L2018 that one was missing a description, but it was proper json

**Comment by sckott** [comment]
@cboettig looks here https://github.com/ropensci/drat/blob/gh-pages/ropensci.R#L11 like you force all repos to have `ropensci/` as the github owner - whereas now we have ropenscilabs as well - or did in interpret that wrong?

**Comment by cboettig** [comment]
Right, that's probably the issue.  Don't think we had labs at the time

**Comment by cboettig** [comment]
@sckott can you edit the `ropensci.R` file to get the right org account as well?  Not sure where that data lives.
